---
title: "Using secsse with complete phylogenies (with extinction)"
author: "Pedro Santos Neves"
date: "2023-07-11"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using secsse with complete phylogenies (with extinction)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(secsse)
  utils::data("example_phy_GeoSSE", package = "secsse")
  traits <- as.numeric(example_phy_GeoSSE$tip.state)
  lambdas <- list()
  lambdas[[1]] <- matrix(0, ncol = 9, nrow = 9, byrow = TRUE)
  lambdas[[1]][2, 1] <- 1.5
  lambdas[[1]][3, 1] <- 0.5
  lambdas[[1]][3, 2] <- 1
  for (i in 2:9) {
    lambdas[[i]] <- lambdas[[1]]
  }
  mus <- rep(0, 9)
  Q <- matrix(stats::runif(81), ncol = 9, nrow = 9, byrow = TRUE)
  parameter <- list()
  parameter[[1]] <- lambdas
  parameter[[2]] <- mus
  parameter[[3]] <- Q

  num_concealed_states <- 3
  sampling_fraction <- c(1, 1, 1)

  # secsse_cla_LL3 <- secsse_loglik(parameter = parameter,
  #                                 phy = example_phy_GeoSSE,
  #                                 traits = traits,
  #                                 num_concealed_states =
  #                                   num_concealed_states,
  #                                 cond = "maddison_cond",
  #                                 root_state_weight = "maddison_weights",
  #                                 sampling_fraction = sampling_fraction,
  #                                 setting_calculation = NULL,
  #                                 see_ancestral_states = FALSE,
  #                                 loglik_penalty = 0,
  #                                 is_complete_tree = FALSE)
  # 
  # secsse_cla_LL4 <- secsse_loglik(parameter = parameter,
  #                                 phy = example_phy_GeoSSE,
  #                                 traits = traits,
  #                                 num_concealed_states =
  #                                   num_concealed_states,
  #                                 cond = "maddison_cond",
  #                                 root_state_weight = "maddison_weights",
  #                                 sampling_fraction = sampling_fraction,
  #                                 setting_calculation = NULL,
  #                                 see_ancestral_states = FALSE,
  #                                 loglik_penalty = 0,
  #                                 is_complete_tree = TRUE)
```
