# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ll threaded
#' @param ll lambdas
#' @param mm mus
#' @param Q qs
#' @param ances vector of ances
#' @param for_time fortime
#' @param states states matrix
#' @param merge_branch_out
#' @param node_M out
#' @param num_threads
#' @return log likelihood
#' @export
calc_ll_threaded <- function(ll, mm, Q, ances, for_time, states, num_threads) {
    .Call(`_secsseCPP_calc_ll_threaded`, ll, mm, Q, ances, for_time, states, num_threads)
}

calThruNodes_cpp <- function(ances, states_R, forTime_R, lambdas, mus, Q, num_threads) {
    .Call(`_secsseCPP_calThruNodes_cpp`, ances, states_R, forTime_R, lambdas, mus, Q, num_threads)
}

calc_cla_ll_threaded <- function(ances, states_R, forTime_R, lambdas, mus, Q, num_threads) {
    .Call(`_secsseCPP_calc_cla_ll_threaded`, ances, states_R, forTime_R, lambdas, mus, Q, num_threads)
}

cla_calThruNodes_cpp <- function(ances, states_R, forTime_R, lambdas, mus, Q) {
    .Call(`_secsseCPP_cla_calThruNodes_cpp`, ances, states_R, forTime_R, lambdas, mus, Q)
}

