# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' ll threaded
#' @param ll lambdas
#' @param mm mus
#' @param Q qs
#' @param ances vector of ances
#' @param for_time fortime
#' @param states states matrix
#' @param merge_branch_out merge_branch_out
#' @param node_M out
#' @param num_threads num_threads
#' @param method integration method
#' @return log likelihood
#' @export
calc_ll_threaded <- function(ll, mm, Q, ances, for_time, states, num_threads, method = "odeint::bulirsch_stoer") {
    .Call(`_secsseCPP_calc_ll_threaded`, ll, mm, Q, ances, for_time, states, num_threads, method)
}

calThruNodes_cpp <- function(ances, states_R, forTime_R, lambdas, mus, Q, num_threads, abstol, reltol, method) {
    .Call(`_secsseCPP_calThruNodes_cpp`, ances, states_R, forTime_R, lambdas, mus, Q, num_threads, abstol, reltol, method)
}

#' cla log likelihood using tbb flow
#' @description cla loglik
#' @param ances ances
#' @param states_R states
#' @param forTime_r ff
#' @param lambdas list of lambdas
#' @param mus vector of mus
#' @param Q q
#' @param num_threads num threads
#' @param method integration method
#' @param is_complete_tree is complete tree?
#' @export
calc_cla_ll_threaded <- function(ances, states_R, forTime_R, lambdas_R, mus_R, Q, num_threads = 1L, method = "odeint::bulirsch_stoer", is_complete_tree = FALSE) {
    .Call(`_secsseCPP_calc_cla_ll_threaded`, ances, states_R, forTime_R, lambdas_R, mus_R, Q, num_threads, method, is_complete_tree)
}

#' function to condition
#' @param d dd
#' @param y yd
#' @param t td
#' @param ll ll
#' @param mm mm
#' @param Q qd
#' @param method method
#' @param atol atol
#' @param rtol rtol
#' @export
ct_condition <- function(d, y, t, ll, mm, Q, method, atol, rtol) {
    .Call(`_secsseCPP_ct_condition`, d, y, t, ll, mm, Q, method, atol, rtol)
}

cla_calThruNodes_cpp <- function(ances, states_R, forTime_R, lambdas, mus, Q, method, atol, rtol, is_complete_tree) {
    .Call(`_secsseCPP_cla_calThruNodes_cpp`, ances, states_R, forTime_R, lambdas, mus, Q, method, atol, rtol, is_complete_tree)
}

