# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calThruNodes_cpp <- function(ances, states_R, forTime_R, lambdas, mus, Q, num_threads) {
    .Call(`_secsseCPP_calThruNodes_cpp`, ances, states_R, forTime_R, lambdas, mus, Q, num_threads)
}

cla_calThruNodes_cpp <- function(ances, states_R, forTime_R, lambdas, mus, Q, method) {
    .Call(`_secsseCPP_cla_calThruNodes_cpp`, ances, states_R, forTime_R, lambdas, mus, Q, method)
}

